spring:
  application:
    name: springLearning

  datasource:
#    url: jdbc:postgresql://ep-purple-leaf-a1wz2tog-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
#    username: neondb_owner
#    password: npg_YnhT6EX4tPJH
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false 
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false 
